import {MigrationInterface, QueryRunner} from "typeorm";

export class CreateJwt1554599991407 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("ALTER TABLE `company` CHANGE `country` `country` varchar(2) NULL");
        await queryRunner.query("ALTER TABLE `company` CHANGE `website` `website` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `company` CHANGE `createTimestamp` `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `company` CHANGE `updateTimestamp` `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `doll_part` CHANGE `createTimestamp` `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `doll_part` CHANGE `updateTimestamp` `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `faceup_artist` CHANGE `country` `country` varchar(2) NULL");
        await queryRunner.query("ALTER TABLE `faceup_artist` CHANGE `website` `website` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `faceup_artist` CHANGE `createTimestamp` `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `faceup_artist` CHANGE `updateTimestamp` `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `doll_wishlist` DROP FOREIGN KEY `FK_a2850a7f7c6a6d8c716ea972486`");
        await queryRunner.query("ALTER TABLE `doll_wishlist` CHANGE `createTimestamp` `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `doll_wishlist` CHANGE `updateTimestamp` `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `doll_wishlist` CHANGE `userId` `userId` bigint NULL");
        await queryRunner.query("ALTER TABLE `subscription_tag` CHANGE `createTimestamp` `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `subscription_tag` CHANGE `updateTimestamp` `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `email_address` CHANGE `createTimestamp` `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `email_address` CHANGE `updateTimestamp` `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `image` DROP FOREIGN KEY `FK_cc59166e5aeebd9acea0abd845c`");
        await queryRunner.query("ALTER TABLE `image` CHANGE `createTimestamp` `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `image` CHANGE `updateTimestamp` `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `image` CHANGE `albumId` `albumId` bigint NULL");
        await queryRunner.query("ALTER TABLE `user` DROP FOREIGN KEY `FK_5c0981de5dc2a2222a1f0574859`");
        await queryRunner.query("ALTER TABLE `user` DROP FOREIGN KEY `FK_5553e135b3d6a0cb0c0becb09ce`");
        await queryRunner.query("ALTER TABLE `user` CHANGE `createTimestamp` `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `user` CHANGE `updateTimestamp` `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `user` CHANGE `profileImageId` `profileImageId` bigint NULL");
        await queryRunner.query("ALTER TABLE `user` CHANGE `emailAddressId` `emailAddressId` bigint NULL");
        await queryRunner.query("ALTER TABLE `user_part` DROP FOREIGN KEY `FK_882be1cd1ec21ea50edce75b2e2`");
        await queryRunner.query("ALTER TABLE `user_part` DROP FOREIGN KEY `FK_0e2e906182f635a7a6ab20cc6fb`");
        await queryRunner.query("ALTER TABLE `user_part` DROP FOREIGN KEY `FK_d21fe36cf76b769d4494d8e8268`");
        await queryRunner.query("ALTER TABLE `user_part` CHANGE `createTimestamp` `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `user_part` CHANGE `updateTimestamp` `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `user_part` CHANGE `userId` `userId` bigint NULL");
        await queryRunner.query("ALTER TABLE `user_part` CHANGE `partId` `partId` bigint NULL");
        await queryRunner.query("ALTER TABLE `user_part` CHANGE `artistId` `artistId` bigint NULL");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_db17395ab11e253b87606606d20`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_bc89ed827068248e583ded6bbb7`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_a3d8ee14a7ae3cf4f64cc679381`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_774e699cd243f305e0f89b2b571`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_9c226690608b2c3ae590b892105`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_df2e0b9340c29b35c9921c0ff99`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_7f84191693dfbb1c1b6781ca1c1`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_c281386c7047921632f365f5d6e`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_f8c55fd3b9650dac63b43b1b8c3`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_c48c09ba943b9cc78ff88273c1b`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_fd011263658689ea37c11eec1c4`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_9f9c0d8c638d94ba3caac00b2a6`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_e310876c935cb971c5c5ea42a7c`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_a3d985b5f329e81e9455d7ae987`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_73b86e35b16e1939c77f9c362bd`");
        await queryRunner.query("ALTER TABLE `doll_configuration` CHANGE `createTimestamp` `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `doll_configuration` CHANGE `updateTimestamp` `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `doll_configuration` CHANGE `headId` `headId` bigint NULL");
        await queryRunner.query("ALTER TABLE `doll_configuration` CHANGE `upperBodyId` `upperBodyId` bigint NULL");
        await queryRunner.query("ALTER TABLE `doll_configuration` CHANGE `lowerBodyId` `lowerBodyId` bigint NULL");
        await queryRunner.query("ALTER TABLE `doll_configuration` CHANGE `rightUpperArmId` `rightUpperArmId` bigint NULL");
        await queryRunner.query("ALTER TABLE `doll_configuration` CHANGE `rightLowerArmId` `rightLowerArmId` bigint NULL");
        await queryRunner.query("ALTER TABLE `doll_configuration` CHANGE `rightHandId` `rightHandId` bigint NULL");
        await queryRunner.query("ALTER TABLE `doll_configuration` CHANGE `leftUpperArmId` `leftUpperArmId` bigint NULL");
        await queryRunner.query("ALTER TABLE `doll_configuration` CHANGE `leftLowerArmId` `leftLowerArmId` bigint NULL");
        await queryRunner.query("ALTER TABLE `doll_configuration` CHANGE `leftHandId` `leftHandId` bigint NULL");
        await queryRunner.query("ALTER TABLE `doll_configuration` CHANGE `rightUpperLegId` `rightUpperLegId` bigint NULL");
        await queryRunner.query("ALTER TABLE `doll_configuration` CHANGE `rightLowerLegId` `rightLowerLegId` bigint NULL");
        await queryRunner.query("ALTER TABLE `doll_configuration` CHANGE `rightFootId` `rightFootId` bigint NULL");
        await queryRunner.query("ALTER TABLE `doll_configuration` CHANGE `leftUpperLegId` `leftUpperLegId` bigint NULL");
        await queryRunner.query("ALTER TABLE `doll_configuration` CHANGE `leftLowerLegId` `leftLowerLegId` bigint NULL");
        await queryRunner.query("ALTER TABLE `doll_configuration` CHANGE `leftFootId` `leftFootId` bigint NULL");
        await queryRunner.query("ALTER TABLE `doll_description` CHANGE `createTimestamp` `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `doll_description` CHANGE `updateTimestamp` `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `doll_history` CHANGE `purchaseDate` `purchaseDate` datetime NULL");
        await queryRunner.query("ALTER TABLE `doll_history` CHANGE `arrivalDate` `arrivalDate` datetime NULL");
        await queryRunner.query("ALTER TABLE `doll_history` CHANGE `purchasedFrom` `purchasedFrom` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `doll_history` CHANGE `paid` `paid` int NULL");
        await queryRunner.query("ALTER TABLE `doll_history` CHANGE `traded` `traded` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `doll_history` CHANGE `tradeValue` `tradeValue` int NULL");
        await queryRunner.query("ALTER TABLE `doll_history` CHANGE `createTimestamp` `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `doll_history` CHANGE `updateTimestamp` `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `doll` DROP FOREIGN KEY `FK_dfa8f5677c7d8c449407eeae5d8`");
        await queryRunner.query("ALTER TABLE `doll` DROP FOREIGN KEY `FK_99898d3f6da09bf47325cc0485d`");
        await queryRunner.query("ALTER TABLE `doll` DROP FOREIGN KEY `FK_69659f61a625ea30ffcac14830d`");
        await queryRunner.query("ALTER TABLE `doll` DROP FOREIGN KEY `FK_4cb7ba9d6ef291e33c03c8704ab`");
        await queryRunner.query("ALTER TABLE `doll` CHANGE `sex` `sex` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `doll` CHANGE `gender` `gender` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `doll` CHANGE `createTimestamp` `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `doll` CHANGE `updateTimestamp` `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `doll` CHANGE `wishlistId` `wishlistId` bigint NULL");
        await queryRunner.query("ALTER TABLE `doll` CHANGE `profileImageId` `profileImageId` bigint NULL");
        await queryRunner.query("ALTER TABLE `doll` CHANGE `descriptionId` `descriptionId` bigint NULL");
        await queryRunner.query("ALTER TABLE `doll` CHANGE `historyId` `historyId` bigint NULL");
        await queryRunner.query("ALTER TABLE `comment` DROP FOREIGN KEY `FK_c0354a9a009d3bb45a08655ce3b`");
        await queryRunner.query("ALTER TABLE `comment` DROP FOREIGN KEY `FK_1b03586f7af11eac99f4fdbf012`");
        await queryRunner.query("ALTER TABLE `comment` DROP FOREIGN KEY `FK_079a04274568f6a6322b4d9954e`");
        await queryRunner.query("ALTER TABLE `comment` DROP FOREIGN KEY `FK_ca59e0a6100f1397dccc9a1fc95`");
        await queryRunner.query("ALTER TABLE `comment` CHANGE `createTimestamp` `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `comment` CHANGE `updateTimestamp` `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `comment` CHANGE `userId` `userId` bigint NULL");
        await queryRunner.query("ALTER TABLE `comment` CHANGE `commentId` `commentId` bigint NULL");
        await queryRunner.query("ALTER TABLE `comment` CHANGE `dollId` `dollId` bigint NULL");
        await queryRunner.query("ALTER TABLE `comment` CHANGE `albumId` `albumId` bigint NULL");
        await queryRunner.query("ALTER TABLE `album` CHANGE `createTimestamp` `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `album` CHANGE `updateTimestamp` `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `doll_wishlist` ADD CONSTRAINT `FK_a2850a7f7c6a6d8c716ea972486` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `image` ADD CONSTRAINT `FK_cc59166e5aeebd9acea0abd845c` FOREIGN KEY (`albumId`) REFERENCES `album`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user` ADD CONSTRAINT `FK_5c0981de5dc2a2222a1f0574859` FOREIGN KEY (`profileImageId`) REFERENCES `image`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user` ADD CONSTRAINT `FK_5553e135b3d6a0cb0c0becb09ce` FOREIGN KEY (`emailAddressId`) REFERENCES `email_address`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user_part` ADD CONSTRAINT `FK_882be1cd1ec21ea50edce75b2e2` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user_part` ADD CONSTRAINT `FK_0e2e906182f635a7a6ab20cc6fb` FOREIGN KEY (`partId`) REFERENCES `doll_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user_part` ADD CONSTRAINT `FK_d21fe36cf76b769d4494d8e8268` FOREIGN KEY (`artistId`) REFERENCES `faceup_artist`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_db17395ab11e253b87606606d20` FOREIGN KEY (`headId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_bc89ed827068248e583ded6bbb7` FOREIGN KEY (`upperBodyId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_a3d8ee14a7ae3cf4f64cc679381` FOREIGN KEY (`lowerBodyId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_774e699cd243f305e0f89b2b571` FOREIGN KEY (`rightUpperArmId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_9c226690608b2c3ae590b892105` FOREIGN KEY (`rightLowerArmId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_df2e0b9340c29b35c9921c0ff99` FOREIGN KEY (`rightHandId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_7f84191693dfbb1c1b6781ca1c1` FOREIGN KEY (`leftUpperArmId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_c281386c7047921632f365f5d6e` FOREIGN KEY (`leftLowerArmId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_f8c55fd3b9650dac63b43b1b8c3` FOREIGN KEY (`leftHandId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_c48c09ba943b9cc78ff88273c1b` FOREIGN KEY (`rightUpperLegId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_fd011263658689ea37c11eec1c4` FOREIGN KEY (`rightLowerLegId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_9f9c0d8c638d94ba3caac00b2a6` FOREIGN KEY (`rightFootId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_e310876c935cb971c5c5ea42a7c` FOREIGN KEY (`leftUpperLegId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_a3d985b5f329e81e9455d7ae987` FOREIGN KEY (`leftLowerLegId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_73b86e35b16e1939c77f9c362bd` FOREIGN KEY (`leftFootId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll` ADD CONSTRAINT `FK_dfa8f5677c7d8c449407eeae5d8` FOREIGN KEY (`wishlistId`) REFERENCES `doll_wishlist`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll` ADD CONSTRAINT `FK_99898d3f6da09bf47325cc0485d` FOREIGN KEY (`profileImageId`) REFERENCES `image`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll` ADD CONSTRAINT `FK_69659f61a625ea30ffcac14830d` FOREIGN KEY (`descriptionId`) REFERENCES `doll_description`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll` ADD CONSTRAINT `FK_4cb7ba9d6ef291e33c03c8704ab` FOREIGN KEY (`historyId`) REFERENCES `doll_history`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `comment` ADD CONSTRAINT `FK_c0354a9a009d3bb45a08655ce3b` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `comment` ADD CONSTRAINT `FK_1b03586f7af11eac99f4fdbf012` FOREIGN KEY (`commentId`) REFERENCES `comment`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `comment` ADD CONSTRAINT `FK_079a04274568f6a6322b4d9954e` FOREIGN KEY (`dollId`) REFERENCES `doll`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `comment` ADD CONSTRAINT `FK_ca59e0a6100f1397dccc9a1fc95` FOREIGN KEY (`albumId`) REFERENCES `album`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("ALTER TABLE `comment` DROP FOREIGN KEY `FK_ca59e0a6100f1397dccc9a1fc95`");
        await queryRunner.query("ALTER TABLE `comment` DROP FOREIGN KEY `FK_079a04274568f6a6322b4d9954e`");
        await queryRunner.query("ALTER TABLE `comment` DROP FOREIGN KEY `FK_1b03586f7af11eac99f4fdbf012`");
        await queryRunner.query("ALTER TABLE `comment` DROP FOREIGN KEY `FK_c0354a9a009d3bb45a08655ce3b`");
        await queryRunner.query("ALTER TABLE `doll` DROP FOREIGN KEY `FK_4cb7ba9d6ef291e33c03c8704ab`");
        await queryRunner.query("ALTER TABLE `doll` DROP FOREIGN KEY `FK_69659f61a625ea30ffcac14830d`");
        await queryRunner.query("ALTER TABLE `doll` DROP FOREIGN KEY `FK_99898d3f6da09bf47325cc0485d`");
        await queryRunner.query("ALTER TABLE `doll` DROP FOREIGN KEY `FK_dfa8f5677c7d8c449407eeae5d8`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_73b86e35b16e1939c77f9c362bd`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_a3d985b5f329e81e9455d7ae987`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_e310876c935cb971c5c5ea42a7c`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_9f9c0d8c638d94ba3caac00b2a6`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_fd011263658689ea37c11eec1c4`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_c48c09ba943b9cc78ff88273c1b`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_f8c55fd3b9650dac63b43b1b8c3`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_c281386c7047921632f365f5d6e`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_7f84191693dfbb1c1b6781ca1c1`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_df2e0b9340c29b35c9921c0ff99`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_9c226690608b2c3ae590b892105`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_774e699cd243f305e0f89b2b571`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_a3d8ee14a7ae3cf4f64cc679381`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_bc89ed827068248e583ded6bbb7`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_db17395ab11e253b87606606d20`");
        await queryRunner.query("ALTER TABLE `user_part` DROP FOREIGN KEY `FK_d21fe36cf76b769d4494d8e8268`");
        await queryRunner.query("ALTER TABLE `user_part` DROP FOREIGN KEY `FK_0e2e906182f635a7a6ab20cc6fb`");
        await queryRunner.query("ALTER TABLE `user_part` DROP FOREIGN KEY `FK_882be1cd1ec21ea50edce75b2e2`");
        await queryRunner.query("ALTER TABLE `user` DROP FOREIGN KEY `FK_5553e135b3d6a0cb0c0becb09ce`");
        await queryRunner.query("ALTER TABLE `user` DROP FOREIGN KEY `FK_5c0981de5dc2a2222a1f0574859`");
        await queryRunner.query("ALTER TABLE `image` DROP FOREIGN KEY `FK_cc59166e5aeebd9acea0abd845c`");
        await queryRunner.query("ALTER TABLE `doll_wishlist` DROP FOREIGN KEY `FK_a2850a7f7c6a6d8c716ea972486`");
        await queryRunner.query("ALTER TABLE `album` CHANGE `updateTimestamp` `updateTimestamp` datetime(6) NOT NULL DEFAULT 'current_timestamp(6)'");
        await queryRunner.query("ALTER TABLE `album` CHANGE `createTimestamp` `createTimestamp` datetime(6) NOT NULL DEFAULT 'current_timestamp(6)'");
        await queryRunner.query("ALTER TABLE `comment` CHANGE `albumId` `albumId` bigint NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `comment` CHANGE `dollId` `dollId` bigint NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `comment` CHANGE `commentId` `commentId` bigint NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `comment` CHANGE `userId` `userId` bigint NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `comment` CHANGE `updateTimestamp` `updateTimestamp` datetime(6) NOT NULL DEFAULT 'current_timestamp(6)'");
        await queryRunner.query("ALTER TABLE `comment` CHANGE `createTimestamp` `createTimestamp` datetime(6) NOT NULL DEFAULT 'current_timestamp(6)'");
        await queryRunner.query("ALTER TABLE `comment` ADD CONSTRAINT `FK_ca59e0a6100f1397dccc9a1fc95` FOREIGN KEY (`albumId`) REFERENCES `album`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `comment` ADD CONSTRAINT `FK_079a04274568f6a6322b4d9954e` FOREIGN KEY (`dollId`) REFERENCES `doll`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `comment` ADD CONSTRAINT `FK_1b03586f7af11eac99f4fdbf012` FOREIGN KEY (`commentId`) REFERENCES `comment`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `comment` ADD CONSTRAINT `FK_c0354a9a009d3bb45a08655ce3b` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll` CHANGE `historyId` `historyId` bigint NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `doll` CHANGE `descriptionId` `descriptionId` bigint NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `doll` CHANGE `profileImageId` `profileImageId` bigint NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `doll` CHANGE `wishlistId` `wishlistId` bigint NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `doll` CHANGE `updateTimestamp` `updateTimestamp` datetime(6) NOT NULL DEFAULT 'current_timestamp(6)'");
        await queryRunner.query("ALTER TABLE `doll` CHANGE `createTimestamp` `createTimestamp` datetime(6) NOT NULL DEFAULT 'current_timestamp(6)'");
        await queryRunner.query("ALTER TABLE `doll` CHANGE `gender` `gender` varchar(255) NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `doll` CHANGE `sex` `sex` varchar(255) NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `doll` ADD CONSTRAINT `FK_4cb7ba9d6ef291e33c03c8704ab` FOREIGN KEY (`historyId`) REFERENCES `doll_history`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll` ADD CONSTRAINT `FK_69659f61a625ea30ffcac14830d` FOREIGN KEY (`descriptionId`) REFERENCES `doll_description`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll` ADD CONSTRAINT `FK_99898d3f6da09bf47325cc0485d` FOREIGN KEY (`profileImageId`) REFERENCES `image`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll` ADD CONSTRAINT `FK_dfa8f5677c7d8c449407eeae5d8` FOREIGN KEY (`wishlistId`) REFERENCES `doll_wishlist`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_history` CHANGE `updateTimestamp` `updateTimestamp` datetime(6) NOT NULL DEFAULT 'current_timestamp(6)'");
        await queryRunner.query("ALTER TABLE `doll_history` CHANGE `createTimestamp` `createTimestamp` datetime(6) NOT NULL DEFAULT 'current_timestamp(6)'");
        await queryRunner.query("ALTER TABLE `doll_history` CHANGE `tradeValue` `tradeValue` int NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `doll_history` CHANGE `traded` `traded` varchar(255) NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `doll_history` CHANGE `paid` `paid` int NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `doll_history` CHANGE `purchasedFrom` `purchasedFrom` varchar(255) NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `doll_history` CHANGE `arrivalDate` `arrivalDate` datetime NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `doll_history` CHANGE `purchaseDate` `purchaseDate` datetime NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `doll_description` CHANGE `updateTimestamp` `updateTimestamp` datetime(6) NOT NULL DEFAULT 'current_timestamp(6)'");
        await queryRunner.query("ALTER TABLE `doll_description` CHANGE `createTimestamp` `createTimestamp` datetime(6) NOT NULL DEFAULT 'current_timestamp(6)'");
        await queryRunner.query("ALTER TABLE `doll_configuration` CHANGE `leftFootId` `leftFootId` bigint NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `doll_configuration` CHANGE `leftLowerLegId` `leftLowerLegId` bigint NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `doll_configuration` CHANGE `leftUpperLegId` `leftUpperLegId` bigint NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `doll_configuration` CHANGE `rightFootId` `rightFootId` bigint NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `doll_configuration` CHANGE `rightLowerLegId` `rightLowerLegId` bigint NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `doll_configuration` CHANGE `rightUpperLegId` `rightUpperLegId` bigint NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `doll_configuration` CHANGE `leftHandId` `leftHandId` bigint NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `doll_configuration` CHANGE `leftLowerArmId` `leftLowerArmId` bigint NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `doll_configuration` CHANGE `leftUpperArmId` `leftUpperArmId` bigint NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `doll_configuration` CHANGE `rightHandId` `rightHandId` bigint NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `doll_configuration` CHANGE `rightLowerArmId` `rightLowerArmId` bigint NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `doll_configuration` CHANGE `rightUpperArmId` `rightUpperArmId` bigint NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `doll_configuration` CHANGE `lowerBodyId` `lowerBodyId` bigint NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `doll_configuration` CHANGE `upperBodyId` `upperBodyId` bigint NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `doll_configuration` CHANGE `headId` `headId` bigint NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `doll_configuration` CHANGE `updateTimestamp` `updateTimestamp` datetime(6) NOT NULL DEFAULT 'current_timestamp(6)'");
        await queryRunner.query("ALTER TABLE `doll_configuration` CHANGE `createTimestamp` `createTimestamp` datetime(6) NOT NULL DEFAULT 'current_timestamp(6)'");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_73b86e35b16e1939c77f9c362bd` FOREIGN KEY (`leftFootId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_a3d985b5f329e81e9455d7ae987` FOREIGN KEY (`leftLowerLegId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_e310876c935cb971c5c5ea42a7c` FOREIGN KEY (`leftUpperLegId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_9f9c0d8c638d94ba3caac00b2a6` FOREIGN KEY (`rightFootId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_fd011263658689ea37c11eec1c4` FOREIGN KEY (`rightLowerLegId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_c48c09ba943b9cc78ff88273c1b` FOREIGN KEY (`rightUpperLegId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_f8c55fd3b9650dac63b43b1b8c3` FOREIGN KEY (`leftHandId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_c281386c7047921632f365f5d6e` FOREIGN KEY (`leftLowerArmId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_7f84191693dfbb1c1b6781ca1c1` FOREIGN KEY (`leftUpperArmId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_df2e0b9340c29b35c9921c0ff99` FOREIGN KEY (`rightHandId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_9c226690608b2c3ae590b892105` FOREIGN KEY (`rightLowerArmId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_774e699cd243f305e0f89b2b571` FOREIGN KEY (`rightUpperArmId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_a3d8ee14a7ae3cf4f64cc679381` FOREIGN KEY (`lowerBodyId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_bc89ed827068248e583ded6bbb7` FOREIGN KEY (`upperBodyId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_db17395ab11e253b87606606d20` FOREIGN KEY (`headId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user_part` CHANGE `artistId` `artistId` bigint NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `user_part` CHANGE `partId` `partId` bigint NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `user_part` CHANGE `userId` `userId` bigint NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `user_part` CHANGE `updateTimestamp` `updateTimestamp` datetime(6) NOT NULL DEFAULT 'current_timestamp(6)'");
        await queryRunner.query("ALTER TABLE `user_part` CHANGE `createTimestamp` `createTimestamp` datetime(6) NOT NULL DEFAULT 'current_timestamp(6)'");
        await queryRunner.query("ALTER TABLE `user_part` ADD CONSTRAINT `FK_d21fe36cf76b769d4494d8e8268` FOREIGN KEY (`artistId`) REFERENCES `faceup_artist`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user_part` ADD CONSTRAINT `FK_0e2e906182f635a7a6ab20cc6fb` FOREIGN KEY (`partId`) REFERENCES `doll_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user_part` ADD CONSTRAINT `FK_882be1cd1ec21ea50edce75b2e2` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user` CHANGE `emailAddressId` `emailAddressId` bigint NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `user` CHANGE `profileImageId` `profileImageId` bigint NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `user` CHANGE `updateTimestamp` `updateTimestamp` datetime(6) NOT NULL DEFAULT 'current_timestamp(6)'");
        await queryRunner.query("ALTER TABLE `user` CHANGE `createTimestamp` `createTimestamp` datetime(6) NOT NULL DEFAULT 'current_timestamp(6)'");
        await queryRunner.query("ALTER TABLE `user` ADD CONSTRAINT `FK_5553e135b3d6a0cb0c0becb09ce` FOREIGN KEY (`emailAddressId`) REFERENCES `email_address`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user` ADD CONSTRAINT `FK_5c0981de5dc2a2222a1f0574859` FOREIGN KEY (`profileImageId`) REFERENCES `image`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `image` CHANGE `albumId` `albumId` bigint NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `image` CHANGE `updateTimestamp` `updateTimestamp` datetime(6) NOT NULL DEFAULT 'current_timestamp(6)'");
        await queryRunner.query("ALTER TABLE `image` CHANGE `createTimestamp` `createTimestamp` datetime(6) NOT NULL DEFAULT 'current_timestamp(6)'");
        await queryRunner.query("ALTER TABLE `image` ADD CONSTRAINT `FK_cc59166e5aeebd9acea0abd845c` FOREIGN KEY (`albumId`) REFERENCES `album`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `email_address` CHANGE `updateTimestamp` `updateTimestamp` datetime(6) NOT NULL DEFAULT 'current_timestamp(6)'");
        await queryRunner.query("ALTER TABLE `email_address` CHANGE `createTimestamp` `createTimestamp` datetime(6) NOT NULL DEFAULT 'current_timestamp(6)'");
        await queryRunner.query("ALTER TABLE `subscription_tag` CHANGE `updateTimestamp` `updateTimestamp` datetime(6) NOT NULL DEFAULT 'current_timestamp(6)'");
        await queryRunner.query("ALTER TABLE `subscription_tag` CHANGE `createTimestamp` `createTimestamp` datetime(6) NOT NULL DEFAULT 'current_timestamp(6)'");
        await queryRunner.query("ALTER TABLE `doll_wishlist` CHANGE `userId` `userId` bigint NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `doll_wishlist` CHANGE `updateTimestamp` `updateTimestamp` datetime(6) NOT NULL DEFAULT 'current_timestamp(6)'");
        await queryRunner.query("ALTER TABLE `doll_wishlist` CHANGE `createTimestamp` `createTimestamp` datetime(6) NOT NULL DEFAULT 'current_timestamp(6)'");
        await queryRunner.query("ALTER TABLE `doll_wishlist` ADD CONSTRAINT `FK_a2850a7f7c6a6d8c716ea972486` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `faceup_artist` CHANGE `updateTimestamp` `updateTimestamp` datetime(6) NOT NULL DEFAULT 'current_timestamp(6)'");
        await queryRunner.query("ALTER TABLE `faceup_artist` CHANGE `createTimestamp` `createTimestamp` datetime(6) NOT NULL DEFAULT 'current_timestamp(6)'");
        await queryRunner.query("ALTER TABLE `faceup_artist` CHANGE `website` `website` varchar(255) NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `faceup_artist` CHANGE `country` `country` varchar(2) NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `doll_part` CHANGE `updateTimestamp` `updateTimestamp` datetime(6) NOT NULL DEFAULT 'current_timestamp(6)'");
        await queryRunner.query("ALTER TABLE `doll_part` CHANGE `createTimestamp` `createTimestamp` datetime(6) NOT NULL DEFAULT 'current_timestamp(6)'");
        await queryRunner.query("ALTER TABLE `company` CHANGE `updateTimestamp` `updateTimestamp` datetime(6) NOT NULL DEFAULT 'current_timestamp(6)'");
        await queryRunner.query("ALTER TABLE `company` CHANGE `createTimestamp` `createTimestamp` datetime(6) NOT NULL DEFAULT 'current_timestamp(6)'");
        await queryRunner.query("ALTER TABLE `company` CHANGE `website` `website` varchar(255) NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `company` CHANGE `country` `country` varchar(2) NULL DEFAULT 'NULL'");
    }

}
