import {MigrationInterface, QueryRunner} from "typeorm";

export class CreateTables1554334857006 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("CREATE TABLE `company` (`id` bigint NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `country` varchar(2) NULL, `website` varchar(255) NULL, `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `doll_part` (`id` bigint NOT NULL AUTO_INCREMENT, `type` varchar(255) NOT NULL, `name` varchar(255) NOT NULL, `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `companyId` bigint NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `faceup_artist` (`id` bigint NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `country` varchar(2) NULL, `website` varchar(255) NULL, `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `doll_configuration` (`id` bigint NOT NULL AUTO_INCREMENT, `height` int NOT NULL, `scale` varchar(255) NOT NULL, `hybridType` varchar(255) NOT NULL, `headIsModded` tinyint NOT NULL DEFAULT 0, `upperBodyIsModded` tinyint NOT NULL DEFAULT 0, `lowerBodyIsModded` tinyint NOT NULL DEFAULT 0, `rightUpperArmIsModded` tinyint NOT NULL DEFAULT 0, `leftUpperArmIsModded` tinyint NOT NULL DEFAULT 0, `rightLowerArmIsModded` tinyint NOT NULL DEFAULT 0, `leftLowerArmIsModded` tinyint NOT NULL DEFAULT 0, `rightHandIsModded` tinyint NOT NULL DEFAULT 0, `leftHandIsModded` tinyint NOT NULL DEFAULT 0, `rightUpperLegIsModded` tinyint NOT NULL DEFAULT 0, `leftUpperLegIsModded` tinyint NOT NULL DEFAULT 0, `rightLowerLegIsModded` tinyint NOT NULL DEFAULT 0, `leftLowerLegIsModded` tinyint NOT NULL DEFAULT 0, `rightFootIsModded` tinyint NOT NULL DEFAULT 0, `leftFootIsModded` tinyint NOT NULL DEFAULT 0, `hasFaceup` tinyint NOT NULL DEFAULT 0, `hasBodyBlush` tinyint NOT NULL DEFAULT 0, `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `dollId` bigint NULL, `headId` bigint NULL, `upperBodyId` bigint NULL, `lowerBodyId` bigint NULL, `rightUpperArmId` bigint NULL, `leftUpperArmId` bigint NULL, `rightLowerArmId` bigint NULL, `leftLowerArmId` bigint NULL, `rightHandId` bigint NULL, `leftHandId` bigint NULL, `rightUpperLegId` bigint NULL, `leftUpperLegId` bigint NULL, `rightLowerLegId` bigint NULL, `leftLowerLegId` bigint NULL, `rightFootId` bigint NULL, `leftFootId` bigint NULL, `faceupArtistId` bigint NULL, `bodyArtistId` bigint NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `doll_description` (`id` bigint NOT NULL AUTO_INCREMENT, `description` text NOT NULL DEFAULT '', `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `doll_history` (`id` bigint NOT NULL AUTO_INCREMENT, `purchaseDate` datetime NULL, `arrivalDate` datetime NULL, `purchasedFrom` varchar(255) NULL, `paid` int NULL, `traded` varchar(255) NULL, `tradeValue` int NULL, `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `image` (`id` bigint NOT NULL AUTO_INCREMENT, `filename` varchar(255) NOT NULL, `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `albumId` bigint NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `doll` (`id` bigint NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `sex` varchar(255) NULL, `gender` varchar(255) NULL, `isSold` tinyint NOT NULL DEFAULT 0, `isWishlist` tinyint NOT NULL DEFAULT 0, `allowComments` tinyint NOT NULL DEFAULT 1, `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `userId` bigint NULL, `profileImageId` bigint NULL, `descriptionId` bigint NULL, `historyId` bigint NULL, UNIQUE INDEX `REL_99898d3f6da09bf47325cc0485` (`profileImageId`), UNIQUE INDEX `REL_69659f61a625ea30ffcac14830` (`descriptionId`), UNIQUE INDEX `REL_4cb7ba9d6ef291e33c03c8704a` (`historyId`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `subscription_tag` (`id` bigint NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `email_address` (`id` bigint NOT NULL AUTO_INCREMENT, `emailAddress` varchar(255) NOT NULL, `softBounces` int NOT NULL DEFAULT 0, `hardBounces` int NOT NULL DEFAULT 0, `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX `IDX_ad251569c1870fb58a945e53ee` (`emailAddress`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `user` (`id` bigint NOT NULL AUTO_INCREMENT, `username` varchar(255) NOT NULL, `password` varchar(255) NOT NULL, `isAdmin` tinyint NOT NULL DEFAULT 0, `isMod` tinyint NOT NULL DEFAULT 0, `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `profileImageId` bigint NULL, `emailAddressId` bigint NULL, UNIQUE INDEX `IDX_78a916df40e02a9deb1c4b75ed` (`username`), UNIQUE INDEX `REL_5c0981de5dc2a2222a1f057485` (`profileImageId`), UNIQUE INDEX `REL_5553e135b3d6a0cb0c0becb09c` (`emailAddressId`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `comment` (`id` bigint NOT NULL AUTO_INCREMENT, `content` text NOT NULL, `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `userId` bigint NULL, `dollId` bigint NULL, `albumId` bigint NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `album` (`id` bigint NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `allowComments` tinyint NOT NULL DEFAULT 1, `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `email_address_categories_subscription_tag` (`emailAddressId` bigint NOT NULL, `subscriptionTagId` bigint NOT NULL, INDEX `IDX_f390f1e603e190b56b070614cd` (`emailAddressId`), INDEX `IDX_23502af2d512f78f7088b504ea` (`subscriptionTagId`), PRIMARY KEY (`emailAddressId`, `subscriptionTagId`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `album_dolls_doll` (`albumId` bigint NOT NULL, `dollId` bigint NOT NULL, INDEX `IDX_c812543d385caf787242d5b179` (`albumId`), INDEX `IDX_03aece4d324f708776ef3e5013` (`dollId`), PRIMARY KEY (`albumId`, `dollId`)) ENGINE=InnoDB");
        await queryRunner.query("ALTER TABLE `doll_part` ADD CONSTRAINT `FK_8e81e45d605454d132d6045da54` FOREIGN KEY (`companyId`) REFERENCES `company`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_49f6884c82bcd0d6b37db8b29ad` FOREIGN KEY (`dollId`) REFERENCES `doll`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_db17395ab11e253b87606606d20` FOREIGN KEY (`headId`) REFERENCES `doll_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_bc89ed827068248e583ded6bbb7` FOREIGN KEY (`upperBodyId`) REFERENCES `doll_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_a3d8ee14a7ae3cf4f64cc679381` FOREIGN KEY (`lowerBodyId`) REFERENCES `doll_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_774e699cd243f305e0f89b2b571` FOREIGN KEY (`rightUpperArmId`) REFERENCES `doll_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_7f84191693dfbb1c1b6781ca1c1` FOREIGN KEY (`leftUpperArmId`) REFERENCES `doll_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_9c226690608b2c3ae590b892105` FOREIGN KEY (`rightLowerArmId`) REFERENCES `doll_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_c281386c7047921632f365f5d6e` FOREIGN KEY (`leftLowerArmId`) REFERENCES `doll_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_df2e0b9340c29b35c9921c0ff99` FOREIGN KEY (`rightHandId`) REFERENCES `doll_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_f8c55fd3b9650dac63b43b1b8c3` FOREIGN KEY (`leftHandId`) REFERENCES `doll_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_c48c09ba943b9cc78ff88273c1b` FOREIGN KEY (`rightUpperLegId`) REFERENCES `doll_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_e310876c935cb971c5c5ea42a7c` FOREIGN KEY (`leftUpperLegId`) REFERENCES `doll_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_fd011263658689ea37c11eec1c4` FOREIGN KEY (`rightLowerLegId`) REFERENCES `doll_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_a3d985b5f329e81e9455d7ae987` FOREIGN KEY (`leftLowerLegId`) REFERENCES `doll_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_9f9c0d8c638d94ba3caac00b2a6` FOREIGN KEY (`rightFootId`) REFERENCES `doll_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_73b86e35b16e1939c77f9c362bd` FOREIGN KEY (`leftFootId`) REFERENCES `doll_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_b1c50ff74623b757e2681686d5a` FOREIGN KEY (`faceupArtistId`) REFERENCES `faceup_artist`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_5cfaa1943d22248cd3983cc1889` FOREIGN KEY (`bodyArtistId`) REFERENCES `faceup_artist`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `image` ADD CONSTRAINT `FK_cc59166e5aeebd9acea0abd845c` FOREIGN KEY (`albumId`) REFERENCES `album`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll` ADD CONSTRAINT `FK_45c01efa2b8776b296d2f874c21` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll` ADD CONSTRAINT `FK_99898d3f6da09bf47325cc0485d` FOREIGN KEY (`profileImageId`) REFERENCES `image`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll` ADD CONSTRAINT `FK_69659f61a625ea30ffcac14830d` FOREIGN KEY (`descriptionId`) REFERENCES `doll_description`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll` ADD CONSTRAINT `FK_4cb7ba9d6ef291e33c03c8704ab` FOREIGN KEY (`historyId`) REFERENCES `doll_history`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user` ADD CONSTRAINT `FK_5c0981de5dc2a2222a1f0574859` FOREIGN KEY (`profileImageId`) REFERENCES `image`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user` ADD CONSTRAINT `FK_5553e135b3d6a0cb0c0becb09ce` FOREIGN KEY (`emailAddressId`) REFERENCES `email_address`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `comment` ADD CONSTRAINT `FK_c0354a9a009d3bb45a08655ce3b` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `comment` ADD CONSTRAINT `FK_079a04274568f6a6322b4d9954e` FOREIGN KEY (`dollId`) REFERENCES `doll`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `comment` ADD CONSTRAINT `FK_ca59e0a6100f1397dccc9a1fc95` FOREIGN KEY (`albumId`) REFERENCES `album`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `email_address_categories_subscription_tag` ADD CONSTRAINT `FK_f390f1e603e190b56b070614cd9` FOREIGN KEY (`emailAddressId`) REFERENCES `email_address`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `email_address_categories_subscription_tag` ADD CONSTRAINT `FK_23502af2d512f78f7088b504ea5` FOREIGN KEY (`subscriptionTagId`) REFERENCES `subscription_tag`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `album_dolls_doll` ADD CONSTRAINT `FK_c812543d385caf787242d5b1791` FOREIGN KEY (`albumId`) REFERENCES `album`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `album_dolls_doll` ADD CONSTRAINT `FK_03aece4d324f708776ef3e5013a` FOREIGN KEY (`dollId`) REFERENCES `doll`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("ALTER TABLE `album_dolls_doll` DROP FOREIGN KEY `FK_03aece4d324f708776ef3e5013a`");
        await queryRunner.query("ALTER TABLE `album_dolls_doll` DROP FOREIGN KEY `FK_c812543d385caf787242d5b1791`");
        await queryRunner.query("ALTER TABLE `email_address_categories_subscription_tag` DROP FOREIGN KEY `FK_23502af2d512f78f7088b504ea5`");
        await queryRunner.query("ALTER TABLE `email_address_categories_subscription_tag` DROP FOREIGN KEY `FK_f390f1e603e190b56b070614cd9`");
        await queryRunner.query("ALTER TABLE `comment` DROP FOREIGN KEY `FK_ca59e0a6100f1397dccc9a1fc95`");
        await queryRunner.query("ALTER TABLE `comment` DROP FOREIGN KEY `FK_079a04274568f6a6322b4d9954e`");
        await queryRunner.query("ALTER TABLE `comment` DROP FOREIGN KEY `FK_c0354a9a009d3bb45a08655ce3b`");
        await queryRunner.query("ALTER TABLE `user` DROP FOREIGN KEY `FK_5553e135b3d6a0cb0c0becb09ce`");
        await queryRunner.query("ALTER TABLE `user` DROP FOREIGN KEY `FK_5c0981de5dc2a2222a1f0574859`");
        await queryRunner.query("ALTER TABLE `doll` DROP FOREIGN KEY `FK_4cb7ba9d6ef291e33c03c8704ab`");
        await queryRunner.query("ALTER TABLE `doll` DROP FOREIGN KEY `FK_69659f61a625ea30ffcac14830d`");
        await queryRunner.query("ALTER TABLE `doll` DROP FOREIGN KEY `FK_99898d3f6da09bf47325cc0485d`");
        await queryRunner.query("ALTER TABLE `doll` DROP FOREIGN KEY `FK_45c01efa2b8776b296d2f874c21`");
        await queryRunner.query("ALTER TABLE `image` DROP FOREIGN KEY `FK_cc59166e5aeebd9acea0abd845c`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_5cfaa1943d22248cd3983cc1889`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_b1c50ff74623b757e2681686d5a`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_73b86e35b16e1939c77f9c362bd`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_9f9c0d8c638d94ba3caac00b2a6`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_a3d985b5f329e81e9455d7ae987`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_fd011263658689ea37c11eec1c4`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_e310876c935cb971c5c5ea42a7c`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_c48c09ba943b9cc78ff88273c1b`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_f8c55fd3b9650dac63b43b1b8c3`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_df2e0b9340c29b35c9921c0ff99`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_c281386c7047921632f365f5d6e`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_9c226690608b2c3ae590b892105`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_7f84191693dfbb1c1b6781ca1c1`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_774e699cd243f305e0f89b2b571`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_a3d8ee14a7ae3cf4f64cc679381`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_bc89ed827068248e583ded6bbb7`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_db17395ab11e253b87606606d20`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_49f6884c82bcd0d6b37db8b29ad`");
        await queryRunner.query("ALTER TABLE `doll_part` DROP FOREIGN KEY `FK_8e81e45d605454d132d6045da54`");
        await queryRunner.query("DROP INDEX `IDX_03aece4d324f708776ef3e5013` ON `album_dolls_doll`");
        await queryRunner.query("DROP INDEX `IDX_c812543d385caf787242d5b179` ON `album_dolls_doll`");
        await queryRunner.query("DROP TABLE `album_dolls_doll`");
        await queryRunner.query("DROP INDEX `IDX_23502af2d512f78f7088b504ea` ON `email_address_categories_subscription_tag`");
        await queryRunner.query("DROP INDEX `IDX_f390f1e603e190b56b070614cd` ON `email_address_categories_subscription_tag`");
        await queryRunner.query("DROP TABLE `email_address_categories_subscription_tag`");
        await queryRunner.query("DROP TABLE `album`");
        await queryRunner.query("DROP TABLE `comment`");
        await queryRunner.query("DROP INDEX `REL_5553e135b3d6a0cb0c0becb09c` ON `user`");
        await queryRunner.query("DROP INDEX `REL_5c0981de5dc2a2222a1f057485` ON `user`");
        await queryRunner.query("DROP INDEX `IDX_78a916df40e02a9deb1c4b75ed` ON `user`");
        await queryRunner.query("DROP TABLE `user`");
        await queryRunner.query("DROP INDEX `IDX_ad251569c1870fb58a945e53ee` ON `email_address`");
        await queryRunner.query("DROP TABLE `email_address`");
        await queryRunner.query("DROP TABLE `subscription_tag`");
        await queryRunner.query("DROP INDEX `REL_4cb7ba9d6ef291e33c03c8704a` ON `doll`");
        await queryRunner.query("DROP INDEX `REL_69659f61a625ea30ffcac14830` ON `doll`");
        await queryRunner.query("DROP INDEX `REL_99898d3f6da09bf47325cc0485` ON `doll`");
        await queryRunner.query("DROP TABLE `doll`");
        await queryRunner.query("DROP TABLE `image`");
        await queryRunner.query("DROP TABLE `doll_history`");
        await queryRunner.query("DROP TABLE `doll_description`");
        await queryRunner.query("DROP TABLE `doll_configuration`");
        await queryRunner.query("DROP TABLE `faceup_artist`");
        await queryRunner.query("DROP TABLE `doll_part`");
        await queryRunner.query("DROP TABLE `company`");
    }

}
