import {MigrationInterface, QueryRunner} from "typeorm";

export class FixTimestampsAndPurchases1555252268907 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("ALTER TABLE `doll` DROP FOREIGN KEY `FK_4cb7ba9d6ef291e33c03c8704ab`");
        await queryRunner.query("DROP INDEX `REL_4cb7ba9d6ef291e33c03c8704a` ON `doll`");
        await queryRunner.query("CREATE TABLE `purchase` (`id` bigint NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `purchaseDate` timestamp NOT NULL, `arrivalDate` timestamp NOT NULL, `purchasePrice` int NULL DEFAULT null, `shippingPrice` int NULL DEFAULT null, `deleteTimestamp` timestamp NULL, `createTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(), `updateTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(), `userId` bigint NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("ALTER TABLE `doll` DROP COLUMN `historyId`");
        await queryRunner.query("ALTER TABLE `user_part` ADD `purchaseId` bigint NULL");
        await queryRunner.query("ALTER TABLE `resin_color` DROP COLUMN `createTimestamp`");
        await queryRunner.query("ALTER TABLE `resin_color` ADD `createTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `resin_color` DROP COLUMN `updateTimestamp`");
        await queryRunner.query("ALTER TABLE `resin_color` ADD `updateTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `faceup_artist` DROP COLUMN `createTimestamp`");
        await queryRunner.query("ALTER TABLE `faceup_artist` ADD `createTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `faceup_artist` DROP COLUMN `updateTimestamp`");
        await queryRunner.query("ALTER TABLE `faceup_artist` ADD `updateTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `doll_wishlist` DROP COLUMN `deleteTimestamp`");
        await queryRunner.query("ALTER TABLE `doll_wishlist` ADD `deleteTimestamp` timestamp NULL");
        await queryRunner.query("ALTER TABLE `doll_wishlist` DROP COLUMN `createTimestamp`");
        await queryRunner.query("ALTER TABLE `doll_wishlist` ADD `createTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `doll_wishlist` DROP COLUMN `updateTimestamp`");
        await queryRunner.query("ALTER TABLE `doll_wishlist` ADD `updateTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `subscription_tag` DROP COLUMN `createTimestamp`");
        await queryRunner.query("ALTER TABLE `subscription_tag` ADD `createTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `subscription_tag` DROP COLUMN `updateTimestamp`");
        await queryRunner.query("ALTER TABLE `subscription_tag` ADD `updateTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `email_address` DROP COLUMN `createTimestamp`");
        await queryRunner.query("ALTER TABLE `email_address` ADD `createTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `email_address` DROP COLUMN `updateTimestamp`");
        await queryRunner.query("ALTER TABLE `email_address` ADD `updateTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `image` DROP COLUMN `deleteTimestamp`");
        await queryRunner.query("ALTER TABLE `image` ADD `deleteTimestamp` timestamp NULL");
        await queryRunner.query("ALTER TABLE `image` DROP COLUMN `createTimestamp`");
        await queryRunner.query("ALTER TABLE `image` ADD `createTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `image` DROP COLUMN `updateTimestamp`");
        await queryRunner.query("ALTER TABLE `image` ADD `updateTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("DROP INDEX `IDX_5c91ca06d455222ff086105130` ON `jwt`");
        await queryRunner.query("ALTER TABLE `jwt` DROP COLUMN `createTimestamp`");
        await queryRunner.query("ALTER TABLE `jwt` ADD `createTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `jwt` DROP COLUMN `updateTimestamp`");
        await queryRunner.query("ALTER TABLE `jwt` ADD `updateTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `user_description` DROP COLUMN `createTimestamp`");
        await queryRunner.query("ALTER TABLE `user_description` ADD `createTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `user_description` DROP COLUMN `updateTimestamp`");
        await queryRunner.query("ALTER TABLE `user_description` ADD `updateTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `user` DROP COLUMN `createTimestamp`");
        await queryRunner.query("ALTER TABLE `user` ADD `createTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `user` DROP COLUMN `updateTimestamp`");
        await queryRunner.query("ALTER TABLE `user` ADD `updateTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `social_media_link` DROP COLUMN `createTimestamp`");
        await queryRunner.query("ALTER TABLE `social_media_link` ADD `createTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `social_media_link` DROP COLUMN `updateTimestamp`");
        await queryRunner.query("ALTER TABLE `social_media_link` ADD `updateTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `company` DROP COLUMN `createTimestamp`");
        await queryRunner.query("ALTER TABLE `company` ADD `createTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `company` DROP COLUMN `updateTimestamp`");
        await queryRunner.query("ALTER TABLE `company` ADD `updateTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `doll_part` DROP COLUMN `createTimestamp`");
        await queryRunner.query("ALTER TABLE `doll_part` ADD `createTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `doll_part` DROP COLUMN `updateTimestamp`");
        await queryRunner.query("ALTER TABLE `doll_part` ADD `updateTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `user_part` DROP COLUMN `createTimestamp`");
        await queryRunner.query("ALTER TABLE `user_part` ADD `createTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `user_part` DROP COLUMN `updateTimestamp`");
        await queryRunner.query("ALTER TABLE `user_part` ADD `updateTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP COLUMN `deleteTimestamp`");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD `deleteTimestamp` timestamp NULL");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP COLUMN `createTimestamp`");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD `createTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP COLUMN `updateTimestamp`");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD `updateTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `doll_description` DROP COLUMN `createTimestamp`");
        await queryRunner.query("ALTER TABLE `doll_description` ADD `createTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `doll_description` DROP COLUMN `updateTimestamp`");
        await queryRunner.query("ALTER TABLE `doll_description` ADD `updateTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `doll` DROP COLUMN `deleteTimestamp`");
        await queryRunner.query("ALTER TABLE `doll` ADD `deleteTimestamp` timestamp NULL");
        await queryRunner.query("ALTER TABLE `doll` DROP COLUMN `createTimestamp`");
        await queryRunner.query("ALTER TABLE `doll` ADD `createTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `doll` DROP COLUMN `updateTimestamp`");
        await queryRunner.query("ALTER TABLE `doll` ADD `updateTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `comment` DROP COLUMN `deleteTimestamp`");
        await queryRunner.query("ALTER TABLE `comment` ADD `deleteTimestamp` timestamp NULL");
        await queryRunner.query("ALTER TABLE `comment` DROP COLUMN `createTimestamp`");
        await queryRunner.query("ALTER TABLE `comment` ADD `createTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `comment` DROP COLUMN `updateTimestamp`");
        await queryRunner.query("ALTER TABLE `comment` ADD `updateTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `album` DROP COLUMN `deleteTimestamp`");
        await queryRunner.query("ALTER TABLE `album` ADD `deleteTimestamp` timestamp NULL");
        await queryRunner.query("ALTER TABLE `album` DROP COLUMN `createTimestamp`");
        await queryRunner.query("ALTER TABLE `album` ADD `createTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `album` DROP COLUMN `updateTimestamp`");
        await queryRunner.query("ALTER TABLE `album` ADD `updateTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()");
        await queryRunner.query("CREATE INDEX `IDX_5c91ca06d455222ff086105130` ON `jwt` (`createTimestamp`)");
        await queryRunner.query("ALTER TABLE `purchase` ADD CONSTRAINT `FK_33520b6c46e1b3971c0a649d38b` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user_part` ADD CONSTRAINT `FK_6a7fcebb65565235c7cd00f9eb1` FOREIGN KEY (`purchaseId`) REFERENCES `purchase`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("ALTER TABLE `user_part` DROP FOREIGN KEY `FK_6a7fcebb65565235c7cd00f9eb1`");
        await queryRunner.query("ALTER TABLE `purchase` DROP FOREIGN KEY `FK_33520b6c46e1b3971c0a649d38b`");
        await queryRunner.query("DROP INDEX `IDX_5c91ca06d455222ff086105130` ON `jwt`");
        await queryRunner.query("ALTER TABLE `album` DROP COLUMN `updateTimestamp`");
        await queryRunner.query("ALTER TABLE `album` ADD `updateTimestamp` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("ALTER TABLE `album` DROP COLUMN `createTimestamp`");
        await queryRunner.query("ALTER TABLE `album` ADD `createTimestamp` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("ALTER TABLE `album` DROP COLUMN `deleteTimestamp`");
        await queryRunner.query("ALTER TABLE `album` ADD `deleteTimestamp` datetime NULL");
        await queryRunner.query("ALTER TABLE `comment` DROP COLUMN `updateTimestamp`");
        await queryRunner.query("ALTER TABLE `comment` ADD `updateTimestamp` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("ALTER TABLE `comment` DROP COLUMN `createTimestamp`");
        await queryRunner.query("ALTER TABLE `comment` ADD `createTimestamp` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("ALTER TABLE `comment` DROP COLUMN `deleteTimestamp`");
        await queryRunner.query("ALTER TABLE `comment` ADD `deleteTimestamp` datetime NULL");
        await queryRunner.query("ALTER TABLE `doll` DROP COLUMN `updateTimestamp`");
        await queryRunner.query("ALTER TABLE `doll` ADD `updateTimestamp` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("ALTER TABLE `doll` DROP COLUMN `createTimestamp`");
        await queryRunner.query("ALTER TABLE `doll` ADD `createTimestamp` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("ALTER TABLE `doll` DROP COLUMN `deleteTimestamp`");
        await queryRunner.query("ALTER TABLE `doll` ADD `deleteTimestamp` datetime NULL");
        await queryRunner.query("ALTER TABLE `doll_description` DROP COLUMN `updateTimestamp`");
        await queryRunner.query("ALTER TABLE `doll_description` ADD `updateTimestamp` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("ALTER TABLE `doll_description` DROP COLUMN `createTimestamp`");
        await queryRunner.query("ALTER TABLE `doll_description` ADD `createTimestamp` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP COLUMN `updateTimestamp`");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD `updateTimestamp` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP COLUMN `createTimestamp`");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD `createTimestamp` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP COLUMN `deleteTimestamp`");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD `deleteTimestamp` datetime NULL");
        await queryRunner.query("ALTER TABLE `user_part` DROP COLUMN `updateTimestamp`");
        await queryRunner.query("ALTER TABLE `user_part` ADD `updateTimestamp` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("ALTER TABLE `user_part` DROP COLUMN `createTimestamp`");
        await queryRunner.query("ALTER TABLE `user_part` ADD `createTimestamp` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("ALTER TABLE `doll_part` DROP COLUMN `updateTimestamp`");
        await queryRunner.query("ALTER TABLE `doll_part` ADD `updateTimestamp` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("ALTER TABLE `doll_part` DROP COLUMN `createTimestamp`");
        await queryRunner.query("ALTER TABLE `doll_part` ADD `createTimestamp` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("ALTER TABLE `company` DROP COLUMN `updateTimestamp`");
        await queryRunner.query("ALTER TABLE `company` ADD `updateTimestamp` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("ALTER TABLE `company` DROP COLUMN `createTimestamp`");
        await queryRunner.query("ALTER TABLE `company` ADD `createTimestamp` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("ALTER TABLE `social_media_link` DROP COLUMN `updateTimestamp`");
        await queryRunner.query("ALTER TABLE `social_media_link` ADD `updateTimestamp` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("ALTER TABLE `social_media_link` DROP COLUMN `createTimestamp`");
        await queryRunner.query("ALTER TABLE `social_media_link` ADD `createTimestamp` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("ALTER TABLE `user` DROP COLUMN `updateTimestamp`");
        await queryRunner.query("ALTER TABLE `user` ADD `updateTimestamp` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("ALTER TABLE `user` DROP COLUMN `createTimestamp`");
        await queryRunner.query("ALTER TABLE `user` ADD `createTimestamp` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("ALTER TABLE `user_description` DROP COLUMN `updateTimestamp`");
        await queryRunner.query("ALTER TABLE `user_description` ADD `updateTimestamp` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("ALTER TABLE `user_description` DROP COLUMN `createTimestamp`");
        await queryRunner.query("ALTER TABLE `user_description` ADD `createTimestamp` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("ALTER TABLE `jwt` DROP COLUMN `updateTimestamp`");
        await queryRunner.query("ALTER TABLE `jwt` ADD `updateTimestamp` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("ALTER TABLE `jwt` DROP COLUMN `createTimestamp`");
        await queryRunner.query("ALTER TABLE `jwt` ADD `createTimestamp` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("CREATE INDEX `IDX_5c91ca06d455222ff086105130` ON `jwt` (`createTimestamp`)");
        await queryRunner.query("ALTER TABLE `image` DROP COLUMN `updateTimestamp`");
        await queryRunner.query("ALTER TABLE `image` ADD `updateTimestamp` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("ALTER TABLE `image` DROP COLUMN `createTimestamp`");
        await queryRunner.query("ALTER TABLE `image` ADD `createTimestamp` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("ALTER TABLE `image` DROP COLUMN `deleteTimestamp`");
        await queryRunner.query("ALTER TABLE `image` ADD `deleteTimestamp` datetime NULL");
        await queryRunner.query("ALTER TABLE `email_address` DROP COLUMN `updateTimestamp`");
        await queryRunner.query("ALTER TABLE `email_address` ADD `updateTimestamp` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("ALTER TABLE `email_address` DROP COLUMN `createTimestamp`");
        await queryRunner.query("ALTER TABLE `email_address` ADD `createTimestamp` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("ALTER TABLE `subscription_tag` DROP COLUMN `updateTimestamp`");
        await queryRunner.query("ALTER TABLE `subscription_tag` ADD `updateTimestamp` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("ALTER TABLE `subscription_tag` DROP COLUMN `createTimestamp`");
        await queryRunner.query("ALTER TABLE `subscription_tag` ADD `createTimestamp` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("ALTER TABLE `doll_wishlist` DROP COLUMN `updateTimestamp`");
        await queryRunner.query("ALTER TABLE `doll_wishlist` ADD `updateTimestamp` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("ALTER TABLE `doll_wishlist` DROP COLUMN `createTimestamp`");
        await queryRunner.query("ALTER TABLE `doll_wishlist` ADD `createTimestamp` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("ALTER TABLE `doll_wishlist` DROP COLUMN `deleteTimestamp`");
        await queryRunner.query("ALTER TABLE `doll_wishlist` ADD `deleteTimestamp` datetime NULL");
        await queryRunner.query("ALTER TABLE `faceup_artist` DROP COLUMN `updateTimestamp`");
        await queryRunner.query("ALTER TABLE `faceup_artist` ADD `updateTimestamp` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("ALTER TABLE `faceup_artist` DROP COLUMN `createTimestamp`");
        await queryRunner.query("ALTER TABLE `faceup_artist` ADD `createTimestamp` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("ALTER TABLE `resin_color` DROP COLUMN `updateTimestamp`");
        await queryRunner.query("ALTER TABLE `resin_color` ADD `updateTimestamp` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("ALTER TABLE `resin_color` DROP COLUMN `createTimestamp`");
        await queryRunner.query("ALTER TABLE `resin_color` ADD `createTimestamp` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("ALTER TABLE `user_part` DROP COLUMN `purchaseId`");
        await queryRunner.query("ALTER TABLE `doll` ADD `historyId` bigint NULL");
        await queryRunner.query("DROP TABLE `purchase`");
        await queryRunner.query("CREATE UNIQUE INDEX `REL_4cb7ba9d6ef291e33c03c8704a` ON `doll` (`historyId`)");
        await queryRunner.query("ALTER TABLE `doll` ADD CONSTRAINT `FK_4cb7ba9d6ef291e33c03c8704ab` FOREIGN KEY (`historyId`) REFERENCES `doll_history`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    }

}
