import {MigrationInterface, QueryRunner} from "typeorm";

export class CreateTables1555180234010 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("CREATE TABLE `resin_color` (`id` bigint NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `colorType` varchar(255) NOT NULL, `type` varchar(255) NOT NULL, `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `companyId` bigint NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `faceup_artist` (`id` bigint NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `country` varchar(2) NULL, `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `doll_wishlist` (`id` bigint NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `isPrivate` tinyint NOT NULL DEFAULT 0, `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `userId` bigint NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `subscription_tag` (`id` bigint NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX `IDX_5386dcb1046ade445e217ba74c` (`name`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `email_address` (`id` bigint NOT NULL AUTO_INCREMENT, `emailAddress` varchar(255) NOT NULL, `softBounces` int NOT NULL DEFAULT 0, `hardBounces` int NOT NULL DEFAULT 0, `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX `IDX_ad251569c1870fb58a945e53ee` (`emailAddress`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `image` (`id` bigint NOT NULL AUTO_INCREMENT, `filename` varchar(255) NOT NULL, `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `userId` bigint NULL, `albumId` bigint NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `jwt` (`id` bigint NOT NULL AUTO_INCREMENT, `token` varchar(255) NOT NULL, `revoked` tinyint NOT NULL DEFAULT 0, `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `userId` bigint NULL, UNIQUE INDEX `IDX_77c04766b3af10daff511d591b` (`token`), INDEX `IDX_5c91ca06d455222ff086105130` (`createTimestamp`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `user_description` (`id` bigint NOT NULL AUTO_INCREMENT, `description` text NOT NULL DEFAULT '', `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `user` (`id` bigint NOT NULL AUTO_INCREMENT, `username` varchar(255) NOT NULL, `password` varchar(255) NOT NULL, `isAdmin` tinyint NOT NULL DEFAULT 0, `isMod` tinyint NOT NULL DEFAULT 0, `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `profileImageId` bigint NULL, `emailAddressId` bigint NULL, `descriptionId` bigint NULL, UNIQUE INDEX `IDX_78a916df40e02a9deb1c4b75ed` (`username`), UNIQUE INDEX `REL_5c0981de5dc2a2222a1f057485` (`profileImageId`), UNIQUE INDEX `REL_5553e135b3d6a0cb0c0becb09c` (`emailAddressId`), UNIQUE INDEX `REL_46438b71d3020578834c493826` (`descriptionId`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `social_media_link` (`id` bigint NOT NULL AUTO_INCREMENT, `url` varchar(255) NOT NULL, `service` varchar(255) NOT NULL, `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `userId` bigint NULL, `artistId` bigint NULL, `companyId` bigint NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `company` (`id` bigint NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `country` varchar(2) NULL, `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `doll_part` (`id` bigint NOT NULL AUTO_INCREMENT, `type` varchar(255) NOT NULL, `name` varchar(255) NOT NULL, `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `companyId` bigint NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `user_part` (`id` bigint NOT NULL AUTO_INCREMENT, `isWishlist` tinyint NOT NULL DEFAULT 0, `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `userId` bigint NULL, `partId` bigint NULL, `artistId` bigint NULL, `resinColorId` bigint NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `doll_configuration` (`id` bigint NOT NULL AUTO_INCREMENT, `height` int NOT NULL, `scale` varchar(255) NOT NULL, `hybridType` varchar(255) NOT NULL, `isPrimary` tinyint NOT NULL DEFAULT 0, `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `dollId` bigint NOT NULL, `headId` bigint NULL, `upperBodyId` bigint NULL, `lowerBodyId` bigint NULL, `rightUpperArmId` bigint NULL, `rightLowerArmId` bigint NULL, `rightHandId` bigint NULL, `leftUpperArmId` bigint NULL, `leftLowerArmId` bigint NULL, `leftHandId` bigint NULL, `rightUpperLegId` bigint NULL, `rightLowerLegId` bigint NULL, `rightFootId` bigint NULL, `leftUpperLegId` bigint NULL, `leftLowerLegId` bigint NULL, `leftFootId` bigint NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `doll_description` (`id` bigint NOT NULL AUTO_INCREMENT, `description` text NOT NULL DEFAULT '', `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `doll_history` (`id` bigint NOT NULL AUTO_INCREMENT, `purchaseDate` datetime NULL, `arrivalDate` datetime NULL, `purchasedFrom` varchar(255) NULL, `paid` int NULL, `traded` varchar(255) NULL, `tradeValue` int NULL, `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `doll` (`id` bigint NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `sex` varchar(255) NULL, `gender` varchar(255) NULL, `isSold` tinyint NOT NULL DEFAULT 0, `isWishlist` tinyint NOT NULL DEFAULT 0, `isPrivate` tinyint NOT NULL DEFAULT 0, `allowComments` tinyint NOT NULL DEFAULT 1, `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `userId` bigint NOT NULL, `wishlistId` bigint NULL, `profileImageId` bigint NULL, `descriptionId` bigint NULL, `historyId` bigint NULL, UNIQUE INDEX `REL_99898d3f6da09bf47325cc0485` (`profileImageId`), UNIQUE INDEX `REL_69659f61a625ea30ffcac14830` (`descriptionId`), UNIQUE INDEX `REL_4cb7ba9d6ef291e33c03c8704a` (`historyId`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `comment` (`id` bigint NOT NULL AUTO_INCREMENT, `content` text NOT NULL, `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `userId` bigint NULL, `commentId` bigint NULL, `dollId` bigint NULL, `albumId` bigint NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `album` (`id` bigint NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `allowComments` tinyint NOT NULL DEFAULT 1, `isPrivate` tinyint NOT NULL DEFAULT 0, `createTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updateTimestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `userId` bigint NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `email_address_categories_subscription_tag` (`emailAddressId` bigint NOT NULL, `subscriptionTagId` bigint NOT NULL, INDEX `IDX_f390f1e603e190b56b070614cd` (`emailAddressId`), INDEX `IDX_23502af2d512f78f7088b504ea` (`subscriptionTagId`), PRIMARY KEY (`emailAddressId`, `subscriptionTagId`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `doll_configuration_extra_parts_user_part` (`dollConfigurationId` bigint NOT NULL, `userPartId` bigint NOT NULL, INDEX `IDX_948ede8f15d42224f3cdb9e518` (`dollConfigurationId`), INDEX `IDX_25c9ff9822e0cec3e04af3aa99` (`userPartId`), PRIMARY KEY (`dollConfigurationId`, `userPartId`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `album_dolls_doll` (`albumId` bigint NOT NULL, `dollId` bigint NOT NULL, INDEX `IDX_c812543d385caf787242d5b179` (`albumId`), INDEX `IDX_03aece4d324f708776ef3e5013` (`dollId`), PRIMARY KEY (`albumId`, `dollId`)) ENGINE=InnoDB");
        await queryRunner.query("ALTER TABLE `resin_color` ADD CONSTRAINT `FK_d083bd6c38066c7b747b3050ef9` FOREIGN KEY (`companyId`) REFERENCES `company`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_wishlist` ADD CONSTRAINT `FK_a2850a7f7c6a6d8c716ea972486` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `image` ADD CONSTRAINT `FK_dc40417dfa0c7fbd70b8eb880cc` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `image` ADD CONSTRAINT `FK_cc59166e5aeebd9acea0abd845c` FOREIGN KEY (`albumId`) REFERENCES `album`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `jwt` ADD CONSTRAINT `FK_690dc6b83bb053b2ccd4342a17f` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user` ADD CONSTRAINT `FK_5c0981de5dc2a2222a1f0574859` FOREIGN KEY (`profileImageId`) REFERENCES `image`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user` ADD CONSTRAINT `FK_5553e135b3d6a0cb0c0becb09ce` FOREIGN KEY (`emailAddressId`) REFERENCES `email_address`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user` ADD CONSTRAINT `FK_46438b71d3020578834c493826b` FOREIGN KEY (`descriptionId`) REFERENCES `user_description`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `social_media_link` ADD CONSTRAINT `FK_86d4f4762605fdf5fb04c75b5af` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `social_media_link` ADD CONSTRAINT `FK_b1624615aef7bcbe4182b565bf0` FOREIGN KEY (`artistId`) REFERENCES `faceup_artist`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `social_media_link` ADD CONSTRAINT `FK_31b79a922431b5954b37f57a487` FOREIGN KEY (`companyId`) REFERENCES `company`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_part` ADD CONSTRAINT `FK_8e81e45d605454d132d6045da54` FOREIGN KEY (`companyId`) REFERENCES `company`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user_part` ADD CONSTRAINT `FK_882be1cd1ec21ea50edce75b2e2` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user_part` ADD CONSTRAINT `FK_0e2e906182f635a7a6ab20cc6fb` FOREIGN KEY (`partId`) REFERENCES `doll_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user_part` ADD CONSTRAINT `FK_d21fe36cf76b769d4494d8e8268` FOREIGN KEY (`artistId`) REFERENCES `faceup_artist`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user_part` ADD CONSTRAINT `FK_c00b29b241e4c503fbb1ec94f00` FOREIGN KEY (`resinColorId`) REFERENCES `resin_color`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_49f6884c82bcd0d6b37db8b29ad` FOREIGN KEY (`dollId`) REFERENCES `doll`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_db17395ab11e253b87606606d20` FOREIGN KEY (`headId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_bc89ed827068248e583ded6bbb7` FOREIGN KEY (`upperBodyId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_a3d8ee14a7ae3cf4f64cc679381` FOREIGN KEY (`lowerBodyId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_774e699cd243f305e0f89b2b571` FOREIGN KEY (`rightUpperArmId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_9c226690608b2c3ae590b892105` FOREIGN KEY (`rightLowerArmId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_df2e0b9340c29b35c9921c0ff99` FOREIGN KEY (`rightHandId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_7f84191693dfbb1c1b6781ca1c1` FOREIGN KEY (`leftUpperArmId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_c281386c7047921632f365f5d6e` FOREIGN KEY (`leftLowerArmId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_f8c55fd3b9650dac63b43b1b8c3` FOREIGN KEY (`leftHandId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_c48c09ba943b9cc78ff88273c1b` FOREIGN KEY (`rightUpperLegId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_fd011263658689ea37c11eec1c4` FOREIGN KEY (`rightLowerLegId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_9f9c0d8c638d94ba3caac00b2a6` FOREIGN KEY (`rightFootId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_e310876c935cb971c5c5ea42a7c` FOREIGN KEY (`leftUpperLegId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_a3d985b5f329e81e9455d7ae987` FOREIGN KEY (`leftLowerLegId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration` ADD CONSTRAINT `FK_73b86e35b16e1939c77f9c362bd` FOREIGN KEY (`leftFootId`) REFERENCES `user_part`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll` ADD CONSTRAINT `FK_45c01efa2b8776b296d2f874c21` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll` ADD CONSTRAINT `FK_dfa8f5677c7d8c449407eeae5d8` FOREIGN KEY (`wishlistId`) REFERENCES `doll_wishlist`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll` ADD CONSTRAINT `FK_99898d3f6da09bf47325cc0485d` FOREIGN KEY (`profileImageId`) REFERENCES `image`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll` ADD CONSTRAINT `FK_69659f61a625ea30ffcac14830d` FOREIGN KEY (`descriptionId`) REFERENCES `doll_description`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll` ADD CONSTRAINT `FK_4cb7ba9d6ef291e33c03c8704ab` FOREIGN KEY (`historyId`) REFERENCES `doll_history`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `comment` ADD CONSTRAINT `FK_c0354a9a009d3bb45a08655ce3b` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `comment` ADD CONSTRAINT `FK_1b03586f7af11eac99f4fdbf012` FOREIGN KEY (`commentId`) REFERENCES `comment`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `comment` ADD CONSTRAINT `FK_079a04274568f6a6322b4d9954e` FOREIGN KEY (`dollId`) REFERENCES `doll`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `comment` ADD CONSTRAINT `FK_ca59e0a6100f1397dccc9a1fc95` FOREIGN KEY (`albumId`) REFERENCES `album`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `album` ADD CONSTRAINT `FK_815bbf84cb5e82a56c85294d0fe` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `email_address_categories_subscription_tag` ADD CONSTRAINT `FK_f390f1e603e190b56b070614cd9` FOREIGN KEY (`emailAddressId`) REFERENCES `email_address`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `email_address_categories_subscription_tag` ADD CONSTRAINT `FK_23502af2d512f78f7088b504ea5` FOREIGN KEY (`subscriptionTagId`) REFERENCES `subscription_tag`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration_extra_parts_user_part` ADD CONSTRAINT `FK_948ede8f15d42224f3cdb9e5189` FOREIGN KEY (`dollConfigurationId`) REFERENCES `doll_configuration`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `doll_configuration_extra_parts_user_part` ADD CONSTRAINT `FK_25c9ff9822e0cec3e04af3aa99e` FOREIGN KEY (`userPartId`) REFERENCES `user_part`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `album_dolls_doll` ADD CONSTRAINT `FK_c812543d385caf787242d5b1791` FOREIGN KEY (`albumId`) REFERENCES `album`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `album_dolls_doll` ADD CONSTRAINT `FK_03aece4d324f708776ef3e5013a` FOREIGN KEY (`dollId`) REFERENCES `doll`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("ALTER TABLE `album_dolls_doll` DROP FOREIGN KEY `FK_03aece4d324f708776ef3e5013a`");
        await queryRunner.query("ALTER TABLE `album_dolls_doll` DROP FOREIGN KEY `FK_c812543d385caf787242d5b1791`");
        await queryRunner.query("ALTER TABLE `doll_configuration_extra_parts_user_part` DROP FOREIGN KEY `FK_25c9ff9822e0cec3e04af3aa99e`");
        await queryRunner.query("ALTER TABLE `doll_configuration_extra_parts_user_part` DROP FOREIGN KEY `FK_948ede8f15d42224f3cdb9e5189`");
        await queryRunner.query("ALTER TABLE `email_address_categories_subscription_tag` DROP FOREIGN KEY `FK_23502af2d512f78f7088b504ea5`");
        await queryRunner.query("ALTER TABLE `email_address_categories_subscription_tag` DROP FOREIGN KEY `FK_f390f1e603e190b56b070614cd9`");
        await queryRunner.query("ALTER TABLE `album` DROP FOREIGN KEY `FK_815bbf84cb5e82a56c85294d0fe`");
        await queryRunner.query("ALTER TABLE `comment` DROP FOREIGN KEY `FK_ca59e0a6100f1397dccc9a1fc95`");
        await queryRunner.query("ALTER TABLE `comment` DROP FOREIGN KEY `FK_079a04274568f6a6322b4d9954e`");
        await queryRunner.query("ALTER TABLE `comment` DROP FOREIGN KEY `FK_1b03586f7af11eac99f4fdbf012`");
        await queryRunner.query("ALTER TABLE `comment` DROP FOREIGN KEY `FK_c0354a9a009d3bb45a08655ce3b`");
        await queryRunner.query("ALTER TABLE `doll` DROP FOREIGN KEY `FK_4cb7ba9d6ef291e33c03c8704ab`");
        await queryRunner.query("ALTER TABLE `doll` DROP FOREIGN KEY `FK_69659f61a625ea30ffcac14830d`");
        await queryRunner.query("ALTER TABLE `doll` DROP FOREIGN KEY `FK_99898d3f6da09bf47325cc0485d`");
        await queryRunner.query("ALTER TABLE `doll` DROP FOREIGN KEY `FK_dfa8f5677c7d8c449407eeae5d8`");
        await queryRunner.query("ALTER TABLE `doll` DROP FOREIGN KEY `FK_45c01efa2b8776b296d2f874c21`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_73b86e35b16e1939c77f9c362bd`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_a3d985b5f329e81e9455d7ae987`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_e310876c935cb971c5c5ea42a7c`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_9f9c0d8c638d94ba3caac00b2a6`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_fd011263658689ea37c11eec1c4`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_c48c09ba943b9cc78ff88273c1b`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_f8c55fd3b9650dac63b43b1b8c3`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_c281386c7047921632f365f5d6e`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_7f84191693dfbb1c1b6781ca1c1`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_df2e0b9340c29b35c9921c0ff99`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_9c226690608b2c3ae590b892105`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_774e699cd243f305e0f89b2b571`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_a3d8ee14a7ae3cf4f64cc679381`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_bc89ed827068248e583ded6bbb7`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_db17395ab11e253b87606606d20`");
        await queryRunner.query("ALTER TABLE `doll_configuration` DROP FOREIGN KEY `FK_49f6884c82bcd0d6b37db8b29ad`");
        await queryRunner.query("ALTER TABLE `user_part` DROP FOREIGN KEY `FK_c00b29b241e4c503fbb1ec94f00`");
        await queryRunner.query("ALTER TABLE `user_part` DROP FOREIGN KEY `FK_d21fe36cf76b769d4494d8e8268`");
        await queryRunner.query("ALTER TABLE `user_part` DROP FOREIGN KEY `FK_0e2e906182f635a7a6ab20cc6fb`");
        await queryRunner.query("ALTER TABLE `user_part` DROP FOREIGN KEY `FK_882be1cd1ec21ea50edce75b2e2`");
        await queryRunner.query("ALTER TABLE `doll_part` DROP FOREIGN KEY `FK_8e81e45d605454d132d6045da54`");
        await queryRunner.query("ALTER TABLE `social_media_link` DROP FOREIGN KEY `FK_31b79a922431b5954b37f57a487`");
        await queryRunner.query("ALTER TABLE `social_media_link` DROP FOREIGN KEY `FK_b1624615aef7bcbe4182b565bf0`");
        await queryRunner.query("ALTER TABLE `social_media_link` DROP FOREIGN KEY `FK_86d4f4762605fdf5fb04c75b5af`");
        await queryRunner.query("ALTER TABLE `user` DROP FOREIGN KEY `FK_46438b71d3020578834c493826b`");
        await queryRunner.query("ALTER TABLE `user` DROP FOREIGN KEY `FK_5553e135b3d6a0cb0c0becb09ce`");
        await queryRunner.query("ALTER TABLE `user` DROP FOREIGN KEY `FK_5c0981de5dc2a2222a1f0574859`");
        await queryRunner.query("ALTER TABLE `jwt` DROP FOREIGN KEY `FK_690dc6b83bb053b2ccd4342a17f`");
        await queryRunner.query("ALTER TABLE `image` DROP FOREIGN KEY `FK_cc59166e5aeebd9acea0abd845c`");
        await queryRunner.query("ALTER TABLE `image` DROP FOREIGN KEY `FK_dc40417dfa0c7fbd70b8eb880cc`");
        await queryRunner.query("ALTER TABLE `doll_wishlist` DROP FOREIGN KEY `FK_a2850a7f7c6a6d8c716ea972486`");
        await queryRunner.query("ALTER TABLE `resin_color` DROP FOREIGN KEY `FK_d083bd6c38066c7b747b3050ef9`");
        await queryRunner.query("DROP INDEX `IDX_03aece4d324f708776ef3e5013` ON `album_dolls_doll`");
        await queryRunner.query("DROP INDEX `IDX_c812543d385caf787242d5b179` ON `album_dolls_doll`");
        await queryRunner.query("DROP TABLE `album_dolls_doll`");
        await queryRunner.query("DROP INDEX `IDX_25c9ff9822e0cec3e04af3aa99` ON `doll_configuration_extra_parts_user_part`");
        await queryRunner.query("DROP INDEX `IDX_948ede8f15d42224f3cdb9e518` ON `doll_configuration_extra_parts_user_part`");
        await queryRunner.query("DROP TABLE `doll_configuration_extra_parts_user_part`");
        await queryRunner.query("DROP INDEX `IDX_23502af2d512f78f7088b504ea` ON `email_address_categories_subscription_tag`");
        await queryRunner.query("DROP INDEX `IDX_f390f1e603e190b56b070614cd` ON `email_address_categories_subscription_tag`");
        await queryRunner.query("DROP TABLE `email_address_categories_subscription_tag`");
        await queryRunner.query("DROP TABLE `album`");
        await queryRunner.query("DROP TABLE `comment`");
        await queryRunner.query("DROP INDEX `REL_4cb7ba9d6ef291e33c03c8704a` ON `doll`");
        await queryRunner.query("DROP INDEX `REL_69659f61a625ea30ffcac14830` ON `doll`");
        await queryRunner.query("DROP INDEX `REL_99898d3f6da09bf47325cc0485` ON `doll`");
        await queryRunner.query("DROP TABLE `doll`");
        await queryRunner.query("DROP TABLE `doll_history`");
        await queryRunner.query("DROP TABLE `doll_description`");
        await queryRunner.query("DROP TABLE `doll_configuration`");
        await queryRunner.query("DROP TABLE `user_part`");
        await queryRunner.query("DROP TABLE `doll_part`");
        await queryRunner.query("DROP TABLE `company`");
        await queryRunner.query("DROP TABLE `social_media_link`");
        await queryRunner.query("DROP INDEX `REL_46438b71d3020578834c493826` ON `user`");
        await queryRunner.query("DROP INDEX `REL_5553e135b3d6a0cb0c0becb09c` ON `user`");
        await queryRunner.query("DROP INDEX `REL_5c0981de5dc2a2222a1f057485` ON `user`");
        await queryRunner.query("DROP INDEX `IDX_78a916df40e02a9deb1c4b75ed` ON `user`");
        await queryRunner.query("DROP TABLE `user`");
        await queryRunner.query("DROP TABLE `user_description`");
        await queryRunner.query("DROP INDEX `IDX_5c91ca06d455222ff086105130` ON `jwt`");
        await queryRunner.query("DROP INDEX `IDX_77c04766b3af10daff511d591b` ON `jwt`");
        await queryRunner.query("DROP TABLE `jwt`");
        await queryRunner.query("DROP TABLE `image`");
        await queryRunner.query("DROP INDEX `IDX_ad251569c1870fb58a945e53ee` ON `email_address`");
        await queryRunner.query("DROP TABLE `email_address`");
        await queryRunner.query("DROP INDEX `IDX_5386dcb1046ade445e217ba74c` ON `subscription_tag`");
        await queryRunner.query("DROP TABLE `subscription_tag`");
        await queryRunner.query("DROP TABLE `doll_wishlist`");
        await queryRunner.query("DROP TABLE `faceup_artist`");
        await queryRunner.query("DROP TABLE `resin_color`");
    }

}
