type DollConfiguration {
  id: ID!
  height: Int
  scale: String
  hybridType: String
  head: UserPart
  upperBody: UserPart
  lowerBody: UserPart
  rightUpperArm: UserPart
  rightLowerArm: UserPart
  rightHand: UserPart
  leftUpperArm: UserPart
  leftLowerArm: UserPart
  leftHand: UserPart
  rightUpperLeg: UserPart
  rightLowerLeg: UserPart
  rightFoot: UserPart
  leftUpperLeg: UserPart
  leftLowerLeg: UserPart
  leftFoot: UserPart
  extraParts: [UserPart!]
}
