extend type Query {
  doll(id: ID!): Doll
}

extend type Mutation {
  createDoll(data: CreateDollInput!): Doll
}

input CreateDollInput {
  name: String!
  isPrivate: Boolean!
  isWishlist: Boolean!
  allowComments: Boolean!
  sex: String
  gender: String
  profileImageId: String
  wishlistId: String
}

type Doll {
  id: ID!
  name: String!
  profileImage: Image
  sex: String
  gender: String
  isSold: Boolean!
  isWishlist: Boolean!
  isPrivate: Boolean!
  allowComments: Boolean!
  user: User!
  description: String
  configurations: [DollConfiguration!]
  comments: [Comment!]
  likes: [Like!]
}
