extend type Query {
  faceupArtist(id: ID!): FaceupArtist
}

type FaceupArtist {
  id: ID!
  name: String!
  country: String
  socialLinks: [SocialMediaLink!]
  addedBy: User
  vetted: Boolean!
  likes: [Like!]
}
