type SocialMediaLink {
  id: ID!
  service: String!
  url: String!
}

extend type Mutation {
  addSocialMediaLink(service: String!, url: String!, ownerId: ID!, ownerType: String!): SocialMediaLink
  editSocialMediaLink(id: ID!, url: String!): SocialMediaLink
  deleteSocialMediaLink(id: ID!): SuccessOutput
}
