query userProfile($username: String!) {
  userByName(username: $username) {
    id
    username
    emailAddress
    description
    socialLinks {
      id
      url
      service
    }
    profileImage {
      id
      thumbnail
    }
    dolls {
      id
      name
      profileImage {
        id
        thumbnail
      }
    }
    albums {
      id
      name
      images {
        id
        thumbnail
      }
    }
  }
}
